### ISSUE TITLE
How to realize distributed by two or more servers

### ISSUE THREAD

**Issue by guozhaotong** [ehcache/ehcache3-samples#35]
Excuse me. 'clustered' gives a sample of distributed cache with terracotta server. But in 'tc-config.xml', there is only one server. I try to add a server but only the first server works. Can you give a sample to show how two or more servers work in the cluster.

**Comment by xjtushilei** [comment]
i want to know how to config the xml ,too. I want to get a HA cluster.

**Comment by rajendarg** [comment]
what about the client can we give , separated url in 
<terracotta:connection url="terracotta://localhost:9410/clustered"/>
as 
<terracotta:connection url="terracotta://localhost:9410/clustered, terracotta://localhost:95100/clustered"/>

and 
URI uri = create("terracotta://localhost:9410/clustered");
as
URI uri = create("terracotta://localhost:9410/clustered, terracotta://localhost:9510/clustered");

**Comment by anthonydahanne** [comment]
hello, if you have 2 servers in your cluster, you can refer to them with : 
```
terracotta://server1:port1,server2:port2
```

But actually, if the 2 servers are up, you can either use terracotta://server1:port1 or terracotta://server2:port2 , because if the server you connect to is passive, it will tell the client to connect to the active; and then the active will return the full topology (server1 and server2)

Makes sense ?

**Comment by guozhaotong** [comment]
Thank you for your clearly explaination. I have one question. Did you mean that if I have two servers with 8G memory, I can store totally 8G values in the cluster?

I wonder whether there is a configuration to realize this kind of distributed ehcache cluster : If I have two servers with 8G memory, can I store totally 16G values in the cluster? Can I get the value of a key by any of the servers?
